// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$0 from "./sections/Hero.tsx";
import * as $$$$$$$1 from "./sections/ParagraphList.tsx";
import * as $$$$$$$2 from "./sections/SimpleTextList.tsx";
import * as $$$$$$$3 from "./sections/Theme.tsx";

const manifest = {
  "sections": {
    "deco-sites/realtime/sections/Hero.tsx": $$$$$$$0,
    "deco-sites/realtime/sections/ParagraphList.tsx": $$$$$$$1,
    "deco-sites/realtime/sections/SimpleTextList.tsx": $$$$$$$2,
    "deco-sites/realtime/sections/Theme.tsx": $$$$$$$3,
  },
  "name": "deco-sites/realtime",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
